import type { IconType } from "react-icons";
import { MdBrush, MdDesignServices, MdPhoto } from "react-icons/md";

import {
  FaCss3,
  FaDocker,
  FaGitAlt,
  FaGithub,
  FaHtml5,
  FaJava,
  FaPython,
  FaReact,
} from "react-icons/fa6";

import {
  SiAppwrite,
  SiEslint,
  SiExpress,
  SiFedora,
  SiFigma,
  SiFramer,
  SiGooglecloud,
  SiGnubash,
  SiJsonwebtokens,
  SiMongodb,
  SiMysql,
  SiNestjs,
  SiNetlify,
  SiNextdotjs,
  SiNodedotjs,
  SiNpm,
  SiPostman,
  SiPrisma,
  SiRadixui,
  SiRender,
  SiRedis,
  SiSass,
  SiSocketdotio,
  SiSupabase,
  SiTailwindcss,
  SiTypescript,
  SiVercel,
  SiWebpack,
  SiJavascript,
  SiC,
  SiNodemon,
} from "react-icons/si";

import { TbBrandCpp } from "react-icons/tb";

export const techIcons = {
  TypeScript: SiTypescript,
  React: FaReact,
  "Next.js": SiNextdotjs,
  "Tailwind CSS": SiTailwindcss,
  JavaScript: SiJavascript,
  "Node.js": SiNodedotjs,
  "Express.js": SiExpress,
  NestJS: SiNestjs,
  "JWT / OAuth": SiJsonwebtokens,
  WebSockets: SiSocketdotio,
  Supabase: SiSupabase,
  MySQL: SiMysql,
  Prisma: SiPrisma,
  MongoDB: SiMongodb,
  Docker: FaDocker,
  "Google Cloud": SiGooglecloud,
  Vercel: SiVercel,
  Render: SiRender,
  Git: FaGitAlt,
  GitHub: FaGithub,
  Postman: SiPostman,
  ESLint: SiEslint,
  HTML5: FaHtml5,
  CSS3: FaCss3,
  SASS: SiSass,
  "React Native": FaReact,
  "Radix UI": SiRadixui,
  "Framer Motion": SiFramer,
  Webpack: SiWebpack,
  NPM: SiNpm,
  Nodemon: SiNodemon,
  Appwrite: SiAppwrite,
  Redis: SiRedis,
  "Linux(Fedora)": SiFedora,
  C: SiC,
  "C++": TbBrandCpp,
  Java: FaJava,
  "Shell (Bash)": SiGnubash,
  Python: FaPython,
  Figma: SiFigma,
  Photoshop: MdPhoto,
  Illustrator: MdBrush,
  XD: MdDesignServices,
  Netlify: SiNetlify,
} as const satisfies Record<string, IconType>;

export type TechIconKey = keyof typeof techIcons;